# Uncomment the next line to define a global platform for your project
# platform :ios, '14.2'

target 'Tomo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for PetSupport
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Alamofire', '~> 5.0'

  # Optionally, include the Swift extensions if you're using Swift.
  #pod 'FirebaseFirestoreSwift'
  use_frameworks!

  target 'TomoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TomoUITests' do
    # Pods for testing
  end

end
